server:
  port: 9191

spring:
  pulsar:
    client:
      service-url: pulsar://localhost:6650
    producer:
      topic-name1: test1
      topic-name2: book-topic
    consumer:
      subscription:
        name: my-subscription
    defaults:
      type-mappings:
        - messageType: com.example.demo.Book
          schema-info:
            schema-type: JSON

